import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Repository = {
  id: number;
  name: string;
  full_name: string;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const res = await fetch('http://api.github.com/repos/vercel/next.js', {
    cache: 'no-store'
  })

  const data: Repository = await res.json()

  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className='text-red-100'>MyFirst Next JS App</h1>
        <h2>{data.full_name}</h2>
        
        {children}
      </body>
    </html>
  )
}
